### ISSUE TITLE
A couple of questions about the tutorial

### ISSUE THREAD

**Issue by Faravidj** [sirkkalap/freenas-crashplan-howto#12]
The how-to is great and straightforward, but a couple of questions remain:

What I have currently setup: a windows machine with crashplan that backups to cloud and to a freenas server behind a VDSL connection, freenas server doesn't have crashplan installed so version cleaning and other maintenance tasks take a really long time for almost 4TB of data and over 300k files.

So I want to setup the freenas server as a crashplan remote computer so it does all the maintenance inside the server instead of transfering all the data over a slow VDSL connection.

But I've got a couple of questions:

For what I see from the instructions, you set up a source and a target for backup in the freenas system?
I don't want to do this, I want to set up freenas crashplan as a remote computer and don't want to backup anything from the freenas server itself.

After this setup locally:
Looks like I need to uninstall crashplan from the local computer and install a older version to communicate with the server?
Can I use crashplan locally to also backup to cloud after reinstallation and setup of a SSH tunnel, or is it setup to only talk with the freenas crashplan installation?

**Comment by sirkkalap** [comment]
I see that you have issues configuring Crashplan.

This setup on FreeNAS does not change any Crashplan functionality. 

Connecting backup destinations and managing Crashplan is beyond the scope of these instructions.

The instructions are given in the hope that they are helpful, but I have not the time nor resources to resolve issues beyond installation. Alas I have not had time even for that.

If you find help to your questions somewhere, feel free to reopen / comment again.
