### ISSUE TITLE
4.7.0 got released today

### ISSUE THREAD

**Issue by facastagnini** [sirkkalap/freenas-crashplan-howto#13]
As you may know, Crashplan 4.7.0 got released today. It is [a game changing update](https://support.code42.com/CrashPlan/4/Troubleshooting/Computer-To-Computer_Backups_Stop_Working_Between_Version_4.7_And_Earlier_Versions).

The Freenas community is working on updating the Crashplan plugin so it can deal with 4.7.0, you can see the progress here [14994](https://bugs.freenas.org/issues/14994)

In the meanwhile I have been sent to the forums to find the solution, I am testing it right now, I will have a PR tonight.

Federico

Edit: #14

**Comment by sirkkalap** [comment]
Hi,

I added you to collaborators as I am way too rarely here. I hope that helps.

**Comment by facastagnini** [comment]
Thanks man, I will do my best to keep it updated.
