### ISSUE TITLE
documentation outdated

### ISSUE THREAD

**Issue by facastagnini** [sirkkalap/freenas-crashplan-howto#2]
Hi @sirkkalap 

I am dealing with the annoyances of the installation, and since things change a bit, I wonder if you would accept a PR with the instruction updated to the last version of freenas.

Let me know and I can make it.

Thanks for putting this here

**Comment by sirkkalap** [comment]
Sure absolutely welcome. I am currently running FreeNAS-9.2.1.8-RELEASE-x64 (e625626), so any updates can be tested against that by me.

**Comment by facastagnini** [comment]
I just created a PR #3 so you can merge some cool stuff added by @chrisgilmerproj

I build on top of his changes. I sent him a PR (https://github.com/chrisgilmerproj/freenas-crashplan-howto/pull/1) with the updated list of steps necesary to install and run crashplan on freenas 9.3

**Comment by sirkkalap** [comment]
Way to go.

#3 and #4 are now in.

I have not had the courage to update my FreeNAS version to 9.3 and I have also skipped Crashplan for 9 months now because they do not support FreeBSD.

But nice to know this is still an option. And thanks for your contribution.
