### ISSUE TITLE
Can't get Crashplan to update

### ISSUE THREAD

**Issue by rubylaser** [sirkkalap/freenas-crashplan-howto#5]
Hello I have a fresh install of FreeNAS 9.3, but after installing bash in my jail,and symlinking,and setting the SSH tunnel, and connecting with the Crashplan client from my Mac, crashplan is never updated in the jail.  Do you have any ideas to get this working?

```
root@crashplan_1:/ # tail -f /usr/pbi/crashplan-amd64/share/crashplan/log/app.log | grep CPVERSION
CPVERSION    = 3.6.3 - 1388556100363 (2014-01-01T06:01:40:363+0000)
```

**Comment by facastagnini** [comment]
You will have to look closely to the log to figure out what is going on.

```bash
tail -f /usr/pbi/crashplan-amd64/share/crashplan/log/app.log
```

**Comment by Ayysir** [comment]
yeap same here, mine doesnt update...and log has nothing to indicate that its updating

**Comment by facastagnini** [comment]
Yeah, it can be painful.
It took me a couple days to figure out all the steps to get it right.

Please look at [the ticket](https://bugs.freenas.org/issues/12375) that I open to freenas to update the crashplan plugin, I put some more information there.

**Comment by sirkkalap** [comment]
Assuming this is fixed by #7 . Closing.

**Comment by facastagnini** [comment]
Hey guys, can you test the steps in the documentation?
You may have to start from scratch with a clean install of the plugin.

**Comment by Ayysir** [comment]
Still doesn't fix anything....
